# Generated by Django 5.1.6 on 2025-03-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                ("timestamp", models.BigIntegerField()),
                ("base", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("rates", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "expense",
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "expense_category",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(default="", max_length=256)),
            ],
            options={
                "verbose_name_plural": "income",
            },
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "income_category",
            },
        ),
        migrations.CreateModel(
            name="MonthlyExpenseTarget",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("month", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "monthly_expense_target",
            },
        ),
        migrations.CreateModel(
            name="UpcomingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
