# Generated by Django 5.1.3 on 2025-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "income_category",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(max_length=256),
        ),
    ]
