# Generated by Django 5.1.3 on 2025-02-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_incomecategory_expense_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.incomecategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(default="", max_length=256),
        ),
    ]
