# Generated by Django 5.1.6 on 2025-02-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_upcomingpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingPayment',
        ),
    ]
