# Generated by Django 5.1.6 on 2025-03-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_monthlyexpensetarget_target_amount_and_more'),
        ('finance', '0005_upcomingpayment'),
    ]

    operations = [
    ]
