# Generated by Django 5.1.5 on 2025-03-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_merge_20250303_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
